language: c
dist: xenial

branches:
  only:
    master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y dkms linux-headers-$(uname -r)

script:
  - sudo dkms build --verbose .
  - sudo dkms install --verbose ch340/1.0.0
